services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    volumes:
      - lubelogger_data:/App/data
      - lubelogger_keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 8080:8080

  telegram-bot:
    build: .
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - lubelogger_bot_data:/data
    env_file:
      - .env
    environment:
      LUBELOGGER_URL: http://app:8080

volumes:
  lubelogger_data:
  lubelogger_keys:
  lubelogger_bot_data:
