services:
  telegram-bot:
    image: ghcr.io/19eddie/lubelogger-telegram-bot:latest
    restart: unless-stopped
    volumes:
      - lubelogger_bot_data:/data
    env_file:
      - .env

volumes:
  lubelogger_bot_data:
